# src/utils/constants.py

TAG_MAP = {
    # .NET
    "c#": "c#",
    "net core": "asp.net core",
    "asp.net api": "asp.net core api",
    "sql-server": "sql server",
    "ef core": "entity framework core",
    "linq": "linq",
    # JS
    "js": "javascript",
    "ts": "typescript",
    "react": "react js",
    "next": "next js",
    "node": "node js",
    # Python
    "ml": "machine learning",
    "dl": "deep learning",
    "nlp": "nlp",
    # Cloud
    "aws": "aws",
    "k8s": "kubernetes",
    "docker": "docker",
    # Others
    "go": "golang",
    "r": "r programming",
    "flutter": "flutter dart",
}

# Maps rich descriptive tags from the API to optimal YouTube search terms.
# The API now generates tags like "Automated Testing with Jest" — these need
# decomposition into core technology + search-friendly modifiers.
DESCRIPTIVE_TAG_DECOMPOSITION = {
    "automated testing": ("testing", "automated testing"),
    "unit testing": ("unit testing", "unit test"),
    "api design": ("api design", "rest api"),
    "restful api": ("rest api", "restful api"),
    "database design": ("database design", "database modeling"),
    "state management": ("state management", "state management"),
    "responsive design": ("responsive design", "responsive web design"),
    "version control": ("git", "version control"),
    "ci/cd": ("ci cd pipeline", "continuous integration"),
    "containerization": ("docker", "containerization"),
    "cloud deployment": ("cloud deployment", "deploy to cloud"),
    "performance optimization": ("performance optimization", "web performance"),
    "security best practices": ("web security", "security best practices"),
    "data modeling": ("data modeling", "database schema"),
    "error handling": ("error handling", "exception handling"),
    "authentication": ("authentication", "auth"),
    "authorization": ("authorization", "role based access"),
}

# Core tech keywords that should be extracted from descriptive tags.
# e.g., "Automated Testing with Jest" → extracts "jest" as the core tech.
CORE_TECH_KEYWORDS = {
    "react",
    "angular",
    "vue",
    "svelte",
    "next",
    "nuxt",
    "gatsby",
    "node",
    "express",
    "fastapi",
    "django",
    "flask",
    "spring",
    "laravel",
    "jest",
    "pytest",
    "cypress",
    "selenium",
    "mocha",
    "vitest",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "mongodb",
    "postgresql",
    "mysql",
    "redis",
    "elasticsearch",
    "graphql",
    "rest",
    "grpc",
    "websocket",
    "typescript",
    "javascript",
    "python",
    "java",
    "c#",
    "go",
    "rust",
    "tailwind",
    "bootstrap",
    "sass",
    "scss",
    "git",
    "github",
    "gitlab",
    "firebase",
    "supabase",
    "prisma",
    "sequelize",
    "webpack",
    "vite",
    "rollup",
    "esbuild",
    "jwt",
    "oauth",
    "passport",
    "redux",
    "zustand",
    "mobx",
    "pinia",
    "vuex",
    "rxjs",
    "ngrx",
}

NEGATIVE_KEYWORDS = [
    "uipath",
    "automation anywhere",
    "blue prism",
    "nice rpa",
    "unity",
    "unreal engine",
    "godot",
    "game dev",
    "minecraft",
    "roblox",
    "xamarin",
    "maui",
    "shorts",
    "tiktok",
    "reels",
    "reaction",
    "review",
    "vlog",
    "rant",
    "unboxing",
    "dumps",
    "exam questions",
    "braindumps",
    "crack",
    "patch",
    "download free",
    "vb.net",
    "visual basic",
]

BEGINNER_KEYWORDS = [
    "from scratch",
    "from zero",
    "beginner",
    "basics",
    "introduction",
    "intro to",
    "101",
    "crash course",
    "start here",
    "absolute beginner",
    "no experience",
    "dummy",
    "dummies",
    "hello world",
    "first app",
    "what is",
    "history of",
    "kids",
    "school",
    "high school",
    "non-programmers",
    "من الصفر",
    "للمبتدئين",
    "مبتدئ",
    "أساسيات",
    "مدخل",
    "شرح بسيط",
    "خطوة بخطوة",
    "مقدمة",
    "الدرس الأول",
    "ما هو",
    "تأسيس",
    "للأطفال",
    "لغير المبرمجين",
    "بدون خبرة",
    "أول تطبيق",
]

UNWANTED_KEYWORDS = [
    "hindi",
    "urdu",
    "bengali",
    "bangla",
    "tamil",
    "telugu",
    "marathi",
    "kannada",
    "malayalam",
    "nepali",
    "sinhala",
    "हिंदी",
    "उर्दू",
    "বাংলা",
    "தமிழ்",
    "తెలుగు",
    "मराठी",
    "ethiopian",
    "amharic",
    "swahili",
    "persian",
    "farsi",
    "turkish",
    "بأማረኛ",
    "spanish",
    "español",
    "curso",
    "lección",
    "portuguese",
    "português",
    "aula",
    "como fazer",
    "russian",
    "pyccкий",
    "german",
    "deutsch",
    "french",
    "français",
    "indonesian",
    "bahasa",
]

KNOWN_BROAD_TOPICS = {
    # Programming Languages
    "python",
    "javascript",
    "java",
    "c",
    "c++",
    "c#",
    "ruby",
    "go",
    "golang",
    "rust",
    "swift",
    "kotlin",
    "typescript",
    "php",
    "scala",
    "perl",
    "r",
    "matlab",
    "julia",
    "haskell",
    "elixir",
    "clojure",
    "lua",
    "dart",
    "objective-c",
    "assembly",
    "fortran",
    "cobol",
    # Web Frontend
    "html",
    "css",
    "sass",
    "scss",
    "tailwind",
    "bootstrap",
    "react",
    "angular",
    "vue",
    "svelte",
    "next.js",
    "nextjs",
    "nuxt",
    "gatsby",
    "jquery",
    # Web Backend
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "nodejs",
    "node.js",
    "express",
    "expressjs",
    "laravel",
    "rails",
    "ruby on rails",
    "asp.net",
    ".net",
    ".net core",
    "nest.js",
    "nestjs",
    # Mobile Development
    "android",
    "ios",
    "flutter",
    "react native",
    "swiftui",
    "jetpack compose",
    "xamarin",
    # DevOps & Cloud
    "docker",
    "kubernetes",
    "k8s",
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "terraform",
    "ansible",
    "jenkins",
    "ci/cd",
    "github actions",
    "gitlab",
    "devops",
    "prometheus",
    "grafana",
    "nginx",
    "apache",
    "helm",
    # Databases
    "sql",
    "mysql",
    "postgresql",
    "postgres",
    "mongodb",
    "redis",
    "elasticsearch",
    "cassandra",
    "dynamodb",
    "sqlite",
    "oracle",
    "neo4j",
    "graphql",
    # Version Control & Tools
    "git",
    "github",
    "linux",
    "unix",
    "bash",
    "shell scripting",
    "powershell",
    "vim",
    "vscode",
    # Data Science & AI
    "dsa",
    "algorithms",
    "data structures",
    "machine learning",
    "deep learning",
    "ai",
    "artificial intelligence",
    "nlp",
    "natural language processing",
    "computer vision",
    "tensorflow",
    "pytorch",
    "keras",
    "scikit-learn",
    "pandas",
    "numpy",
    "data science",
    "data analysis",
    "data engineering",
    "big data",
    "spark",
    "hadoop",
    # Architecture & Design
    "system design",
    "software architecture",
    "microservices",
    "micro services",
    "rest api",
    "restful api",
    "api design",
    "design patterns",
    "oop",
    "object oriented programming",
    "functional programming",
    "clean code",
    "clean architecture",
    "solid principles",
    "domain driven design",
    "ddd",
    "event driven architecture",
    # CS Fundamentals
    "operating systems",
    "networking",
    "computer networks",
    "cybersecurity",
    "cyber security",
    "information security",
    "infosec",
    "ethical hacking",
    "penetration testing",
    "pen testing",
    "network security",
    "application security",
    "cryptography",
    "compilers",
    "databases",
    "distributed systems",
    # Testing
    "testing",
    "unit testing",
    "selenium",
    "cypress",
    "jest",
    "pytest",
    # Other Technologies
    "blockchain",
    "web3",
    "solidity",
    "ethereum",
    "game development",
    "unity",
    "unreal",
    "embedded systems",
    "iot",
    "arduino",
    "raspberry pi",
}

STOP_WORDS = {
    "in",
    "on",
    "at",
    "to",
    "of",
    "is",
    "it",
    "by",
    "an",
    "or",
    "if",
    "do",
    "up",
    "my",
    "me",
    "we",
}
