# src/utils/constants.py

TAG_MAP = {
    # .NET (Minimal Keys to pass Relevance Check)
    "c#": "c#",  # was "c# programming" (Too strict)
    "net core": "asp.net core",
<<<<<<< HEAD
    "asp.net api": "asp.net core api",  # was "asp.net core web api" (Too strict)
=======
    "asp.net api": "asp.net core",  # was "asp.net core web api" (Too strict)
>>>>>>> 51d358c (Improved Youtube Result and Format project using black formatter)
    "sql-server": "sql server",
    "ef core": "entity framework core",
    "linq": "linq",  # was "c# linq" (Too strict)
    # JS
    "js": "javascript",
    "ts": "typescript",
    "react": "react js",
    "next": "next js",
    "node": "node js",
    # Python
    "ml": "machine learning",
    "dl": "deep learning",
    "nlp": "nlp",
    # Cloud
    "aws": "aws",
    "k8s": "kubernetes",
    "docker": "docker",
    # Others
    "go": "golang",
    "r": "r programming",
    "flutter": "flutter dart",
}

NEGATIVE_KEYWORDS = [
    "uipath",
    "automation anywhere",
    "blue prism",
    "nice rpa",
    "unity",
    "unreal engine",
    "godot",
    "game dev",
    "minecraft",
    "roblox",
    "xamarin",
    "maui",
    "shorts",
    "tiktok",
    "reels",
    "reaction",
    "review",
    "vlog",
    "rant",
    "unboxing",
    "dumps",
    "exam questions",
    "braindumps",
    "crack",
    "patch",
    "download free",
    "vb.net",
    "visual basic",
]

BEGINNER_KEYWORDS = [
    "from scratch",
    "from zero",
    "beginner",
    "basics",
    "introduction",
    "intro to",
    "101",
    "crash course",
    "start here",
    "absolute beginner",
    "no experience",
    "dummy",
    "dummies",
    "hello world",
    "first app",
    "what is",
    "history of",
    "kids",
    "school",
    "high school",
    "non-programmers",
    "من الصفر",
    "للمبتدئين",
    "مبتدئ",
    "أساسيات",
    "مدخل",
    "شرح بسيط",
    "خطوة بخطوة",
    "مقدمة",
    "الدرس الأول",
    "ما هو",
    "تأسيس",
    "للأطفال",
    "لغير المبرمجين",
    "بدون خبرة",
    "أول تطبيق",
]

UNWANTED_KEYWORDS = [
    "hindi",
    "urdu",
    "bengali",
    "bangla",
    "tamil",
    "telugu",
    "marathi",
    "kannada",
    "malayalam",
    "nepali",
    "sinhala",
    "हिंदी",
    "उर्दू",
    "বাংলা",
    "தமிழ்",
    "తెలుగు",
    "मराठी",
    "ethiopian",
    "amharic",
    "swahili",
    "persian",
    "farsi",
    "turkish",
    "بأማረኛ",
    "spanish",
    "español",
    "curso",
    "lección",
    "portuguese",
    "português",
    "aula",
    "como fazer",
    "russian",
    "pyccкий",
    "german",
    "deutsch",
    "french",
    "français",
    "indonesian",
    "bahasa",
]
